/**
 * Central API client for the client app.
 *
 * HTTP status is authoritative: a non-2xx response throws an Error that carries
 * the server's own error message (when the body provides one), so callers can
 * surface real failures instead of silently treating them as success. 2xx
 * responses keep returning the raw Response, so existing `.then(r => r.json())`
 * callers are unchanged.
 *
 * Guarantees:
 * - Authorization: the stored admin token is attached unless the caller already
 *   supplied an Authorization header.
 * - FormData: a multipart boundary must be generated by the browser, so a JSON
 *   Content-Type supplied for a FormData body is removed rather than forced.
 * - Errors never contain the token, other request headers or credentials.
 */
export async function apiFetch(path, opts = {}) {
  const base = import.meta.env.VITE_API_URL || '';
  const url = path.startsWith('/') ? `${base}${path}` : `${base}/${path}`;
  // Attach the admin token (if present) so protected endpoints work.
  const token = localStorage.getItem('pa_admin_token');
  const headers = new Headers(opts.headers || {});
  if (token && !headers.has('Authorization')) {
    headers.set('Authorization', `Bearer ${token}`);
  }
  if (isFormData(opts.body) && headers.has('Content-Type')) {
    headers.delete('Content-Type');
  }

  let res;
  try {
    res = await fetch(url, { ...opts, headers });
  } catch (err) {
    // Network-level failure: offline, DNS, connection dropped mid-request
    // (an oversized body can also surface here when the server aborts it).
    const reason = err && err.message ? err.message : 'network error';
    throw new Error(`Could not reach the server (${reason}). Nothing was saved.`);
  }

  if (!res.ok) {
    throw new Error(await describeFailure(res));
  }
  return res;
}

function isFormData(body) {
  return typeof FormData !== 'undefined' && body instanceof FormData;
}

/** Build a safe, user-readable message from a non-2xx response. */
async function describeFailure(res) {
  const status = res.status;
  let serverMessage = '';
  try {
    const contentType = res.headers.get('content-type') || '';
    if (contentType.includes('application/json')) {
      const body = await res.json();
      if (body && typeof body.error === 'string' && body.error.trim()) serverMessage = body.error.trim();
      else if (body && typeof body.message === 'string' && body.message.trim()) serverMessage = body.message.trim();
    } else {
      // HTML (wrong host / SPA fallback), plain text or an empty body.
      const text = (await res.text()).trim();
      if (text && !text.startsWith('<') && text.length <= 200) serverMessage = text;
    }
  } catch {
    serverMessage = ''; // unreadable or already-consumed body
  }
  const label = failureLabel(status);
  return serverMessage ? `${label}: ${serverMessage}` : label;
}

function failureLabel(status) {
  if (status === 401) return 'Admin session rejected (HTTP 401) â please sign in again';
  if (status === 403) return 'Not permitted (HTTP 403)';
  if (status === 413) return 'Upload too large (HTTP 413)';
  if (status === 404) return 'Not found (HTTP 404)';
  if (status >= 500) return `Server error (HTTP ${status})`;
  return `Request rejected (HTTP ${status})`;
}
